.github/workflows/deploy.yml, backend/app.py
Created a .yml file for the CI/CD pipeline. May need to change the Python version depending on what we agree upon, but I left it 3.12 for now.
=> Created .yml file for CI/CD

data/arima_test.py, frontend/src/components/Title.test.tsx, frontend/src/components/Title.tsx, requirements.txt
added back the components folder with its contents
=> Added back components folder and created arima test

data/model_arima.py
For now, the ARIMA model can run in a reasonable way.
Limitations:
The logic behind "number of transactions" and how to mitigate bias: now the number of transactions purely depend on how much data rows we generate.
Mitigating bias: simply dropping rows with bias is not reasonable: this will onyl reduce the number of transactions.
=> Arima Model with graph enhanced

.github/workflows/backend_tests.yml, backend/app.py, backend/test_app.py, backend/tests_app.py
Added some simple backend tests that should be continously updated as we add real features.
=> Alex backend pytests

.github/workflows/Ci.yml, frontend/jest.config.cjs, frontend/package-lock.json, frontend/package.json
=> Frontend-ci-yml-add

backend/app.py, frontend/package-lock.json, frontend/package.json, frontend/src/App.tsx, frontend/src/components/Graph.tsx, frontend/src/components/SelectForecastSize.tsx, frontend/src/types.ts
Connected the /predictValues endpoint to the frontend using a slider and a button inside the SelectForecastSize.tsx component.
Displayed the newly predicted values on the graph in the Graph.tsx component.
IMPORTANT:
I hard coded temporary data into the /getOriginalData and /predictValues endpoints to make this work. The methods to get the real data will be formatted the same and can replace the hard coded data once it's ready.
=> Matthew graph work

backend/read_data.py, backend/read_data_test.py
=> Read_data_functions_and_tests

backend/app.py, backend/read_data.py, backend/test_app.py, frontend/src/components/Graph.tsx
Created this PR again.
Exactly the same changes as I did earlier today (I did everything again because I encountered a GitHub account issue).
Except that:
1. Changed names: from getOriginalData to getPastData
2. getPastData remains getter and filtering_factor disabled (otherwise frontend doesn't show properly at the moment)
=> Eric add endpoints for filter

frontend/src/components/ExportGraphButton.tsx, frontend/src/components/MainPage.tsx, frontend/src/components/PredictButton.tsx
moved around some code thats all
=> organized export graph button

frontend/src/components/Graph.tsx, frontend/src/components/MainPage.tsx
small UI stuff that I did before our presentation
=> added graph axis and labels

.github/workflows/deploy.yml
Added nohup to gunicorn and changed exit command from exit 0 to exit
Also disable gunicorn from printing and sent the logs to /var/log/gunicorn.log
=> Fixed deploy script from never ending and timing out.

.github/workflows/frontend_CI.yml
Update frontend_CI to the node version were usingode20
Updated specification from node18 to n
=> Specify CI versions to what were using

backend/filters.py
Added valid_filter method to Filter class, to follow the Open Closed principle of SOLID
=> Alex filter verification polymorphism

frontend/src/components/UploadDataset.tsx
This will just show whether the file was uploaded or not. Will create an another endpoint to show a list of all available datasets.
=> removed-unnecessary-preview-code

backend/app.py, backend/file_uploader.py, backend/file_uploader_test.py
Gets a list of datasets from our hosted backend. I want to see how it shows up and how we can access It for the graph.
=> tara_add_endpoint

frontend/src/App.tsx, frontend/src/components/GuidancePage/GuidancePage.tsx, frontend/src/components/MainPage.tsx
Added a route to guidance page
=> GuidancePage

frontend/package-lock.json, frontend/package.json, frontend/src/components/Desktop/Desktop.tsx, frontend/src/components/Desktop/style.css, frontend/src/components/ExportGraphButton.tsx, frontend/src/components/GuidancePage/GuidancePage.css, frontend/src/components/GuidancePage/GuidancePage.tsx, frontend/src/components/MainPage.css, frontend/src/components/MainPage.tsx, frontend/src/components/PredictButton.tsx, frontend/src/components/RadioButtons.tsx, frontend/src/components/Slider.tsx
styling for the main components
=> Heather frontend styling and accessibility

frontend/src/components/MainPage.css, frontend/src/components/MainPage.tsx, frontend/src/components/RadioButtons.tsx
Update on UI:
1. Fixed Bar with Menu and Radio Button on it
2. Add a draft revenue Loss sector
I will work on the alignments later
=> MainPage Alignments including Fixed Bar and a new Revenue Loss sector

frontend/src/components/MainPage.css, frontend/src/components/MainPage.tsx
Put the variables on the right
=> Reorganize variables

frontend/src/components/UploadDataset.tsx
=> added go to homepage and to graph buttons

frontend/src/pages/DashboardPage/DashboardPage.css, frontend/src/pages/DashboardPage/DashboardPage.tsx, frontend/src/pages/DashboardPage/components/ExportGraphButton.tsx, frontend/src/pages/DashboardPage/components/PopUpGuidance.tsx, frontend/src/pages/UploadDataset.css, frontend/src/pages/UploadDataset.tsx, frontend/src/services/ExportService.ts
=> Heather Dashboard Guidance changed to Popup

README.md
Added an up-to-date description of our project and goal, along with updated instructions on how to use it. Once we finish moving around files, we'll add the File Structure section. I also added a list of contributors with our github handles. 
Questions for you guys:
1. Are there any other requirements we need to add under Requirements
2. Who do we want to add to Acknowledgements apart from Paul, Mike, Sam, Callum, Julie, and Kyle (we should ask them if they want to be mentioned before adding them)?
=> Carlos readme updates

frontend/index.html, frontend/src/pages/DashboardPage/components/HelpModal.tsx, frontend/src/pages/UploadDataset.tsx
There was an extra tabIndex in two spots that let you focus text youre not supposed to focus
=> fixed ARIA on help modal

frontend/src/pages/DashboardPage/DashboardPage.tsx, frontend/src/pages/DashboardPage/components/Graph.tsx, frontend/src/pages/DashboardPage/components/GraphTypeButtons.tsx, frontend/src/pages/DashboardPage/components/HelpModal.tsx
changed graph colors and colors for the graph type switch
=> fixed color contrast
